[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "prosperity-prop-firm-agent"
version = "0.2.0b6"
description = "Prosperity Labs Propr agent development kit"
requires-python = ">=3.11"
dependencies = ["websockets==17.1"]
readme = "README.md"

[project.scripts]
propfirm = "propfirm.__main__:entrypoint"

[tool.setuptools]
packages = ["propfirm"]
